local _, PlayerClass = UnitClass('player')
PlayerClass = string.lower(PlayerClass)

--[ Keybinding ]--
BINDING_HEADER_QUICKHEAL = "QuickHeal";
BINDING_NAME_QUICKHEAL_HEAL = "Heal";
if PlayerClass == "shaman" then
	BINDING_NAME_QUICKHEAL_HOT = "ChainHeal"
	BINDING_NAME_QUICKHEAL_HOTFH = "ChainHeal Max"
else
	BINDING_NAME_QUICKHEAL_HOT = "HoT";
	BINDING_NAME_QUICKHEAL_HOTFH = "HoT Firehose (Naxx Gargoyles)";
end
BINDING_NAME_QUICKHEAL_HEALSUBGROUP = "Heal Subgroup";
BINDING_NAME_QUICKHEAL_HOTSUBGROUP = "HoT Subgroup";
BINDING_NAME_QUICKHEAL_HEALPARTY = "Heal Party";
BINDING_NAME_QUICKHEAL_HEALMT = "Heal MT";
BINDING_NAME_QUICKHEAL_HOTMT = "HoT MT";
BINDING_NAME_QUICKHEAL_HEALNONMT = "Heal Non MT";
BINDING_NAME_QUICKHEAL_HEALSELF = "Heal Player";
BINDING_NAME_QUICKHEAL_HEALTARGET = "Heal Target";
BINDING_NAME_QUICKHEAL_HEALTARGETTARGET = "Heal Target's Target";
BINDING_NAME_QUICKHEAL_TOGGLEHEALTHYTHRESHOLD = "Toggle Healthy Threshold 0 / 100%"
BINDING_NAME_QUICKHEAL_SHOWDOWNRANKWINDOW = "Show/Hide Downrank Window"


-- Shaman
QUICKHEAL_SPELL_CHAIN_HEAL = "Chain Heal";
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "Lesser Healing Wave";
QUICKHEAL_SPELL_HEALING_WAVE = "Healing Wave";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = 'Lesser Heal';
QUICKHEAL_SPELL_HEAL = 'Heal';
QUICKHEAL_SPELL_GREATER_HEAL = 'Greater Heal';
QUICKHEAL_SPELL_FLASH_HEAL = 'Flash Heal';
QUICKHEAL_SPELL_RENEW = 'Renew';

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = 'Holy Light';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = 'Flash of Light';
QUICKHEAL_SPELL_HOLY_SHOCK = 'Holy Shock';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = 'Healing Touch';
QUICKHEAL_SPELL_REGROWTH = 'Regrowth';
QUICKHEAL_SPELL_REJUVENATION = 'Rejuvenation';
QUICKHEAL_SPELL_SWIFTMEND = 'Swiftmend';
QUICKHEAL_SPELL_TREE_OF_LIFE_FORM = 'Tree Of Life Form';
QUICKHEAL_SPELL_NATURES_SWIFTNESS = "Nature's Swiftness";

FILTER_MTLIST_SHOW = 'Main Tanks';
FILTER_MELEEDPSLIST_SHOW = 'Melee DPS';
FILTER_RANGEDDPSLIST_SHOW = 'Ranged DPS';

QH_STR_MT_PRIO_LIST = 'Main Tanks';
QH_STR_MTLIST = 'Main Tanks';
QH_STR_RANGEDDPSLIST = 'Main Tanks';
QH_CLR_MTLIST = 'C';
QH_CLR_MELEEDPSLIST = 'C';
