if (GetLocale() == "zhCN") then
local _, PlayerClass = UnitClass('player')
PlayerClass = string.lower(PlayerClass)
			
--[ Keybinding ]--
BINDING_HEADER_QUICKHEAL = "QuickHeal（快速治疗插件）";
BINDING_NAME_QUICKHEAL_HEAL = "治疗";
if PlayerClass == "shaman" then
	BINDING_NAME_QUICKHEAL_HOT = "治疗链"
	BINDING_NAME_QUICKHEAL_HOTFH = "治疗链Max"
else
	BINDING_NAME_QUICKHEAL_HOT = "HoT"
	BINDING_NAME_QUICKHEAL_HOTFH = "HoT 火力全开"
end
BINDING_NAME_QUICKHEAL_HEALSUBGROUP = "团队治疗";
BINDING_NAME_QUICKHEAL_HOTSUBGROUP = "团队HoT";
BINDING_NAME_QUICKHEAL_HEALPARTY = "队伍治疗";
BINDING_NAME_QUICKHEAL_HEALMT = "治疗 MT";
BINDING_NAME_QUICKHEAL_HOTMT = "HoT MT";
BINDING_NAME_QUICKHEAL_HEALNONMT = "治疗非MT";
BINDING_NAME_QUICKHEAL_HEALSELF = "治疗自己";
BINDING_NAME_QUICKHEAL_HEALTARGET = "治疗目标";
BINDING_NAME_QUICKHEAL_HEALTARGETTARGET = "治疗目标的目标";
BINDING_NAME_QUICKHEAL_TOGGLEHEALTHYTHRESHOLD = "切换健康阈值 0 / 100%"
BINDING_NAME_QUICKHEAL_SHOWDOWNRANKWINDOW = "显示/隐藏降级窗口"

-- Shaman
QUICKHEAL_SPELL_CHAIN_HEAL = "治疗链";
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "次级治疗波";
QUICKHEAL_SPELL_HEALING_WAVE = "治疗波";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = '次级治疗术';
QUICKHEAL_SPELL_HEAL = '治疗术';
QUICKHEAL_SPELL_GREATER_HEAL = '强效治疗术';
QUICKHEAL_SPELL_FLASH_HEAL = '快速治疗';
QUICKHEAL_SPELL_RENEW = '恢复';

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = '圣光术';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = '圣光闪现';
QUICKHEAL_SPELL_HOLY_SHOCK = '神圣震击';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = '治疗之触';
QUICKHEAL_SPELL_REGROWTH = '愈合';
QUICKHEAL_SPELL_REJUVENATION = '回春术';
QUICKHEAL_SPELL_SWIFTMEND = '迅捷治愈';
QUICKHEAL_SPELL_TREE_OF_LIFE_FORM = '生命之树形态';
QUICKHEAL_SPELL_NATURES_SWIFTNESS = '自然迅捷';

end